# Generated by Django 2.2.16 on 2023-06-30 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.datetime_safe


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Номер задачи')),
                ('status', models.CharField(max_length=200, verbose_name='Статус задачи')),
                ('create_date', models.DateField(default=django.utils.datetime_safe.datetime.now, verbose_name='Дата создания')),
                ('update_date', models.DateField(default=django.utils.datetime_safe.datetime.now, verbose_name='Дата обновления')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель')),
            ],
        ),
    ]
