# Generated by Django 3.2.19 on 2023-06-30 18:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_task_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='number',
            field=models.UUIDField(default=uuid.UUID('e7e829a9-bd8c-486c-ba5f-5a6588739f36'), editable=False, unique=True, verbose_name='Номер задачи'),
        ),
    ]
