# Generated by Django 3.2.19 on 2023-06-30 20:46

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_task_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='create_date',
            field=models.DateField(default=datetime.date(2023, 6, 30), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='task',
            name='number',
            field=models.UUIDField(default=uuid.UUID('903b6000-8d32-416c-811b-d542c43e3635'), editable=False, unique=True, verbose_name='Номер задачи'),
        ),
        migrations.AlterField(
            model_name='task',
            name='update_date',
            field=models.DateField(default=datetime.date(2023, 6, 30), verbose_name='Дата обновления'),
        ),
    ]
