# Generated by Django 3.2.19 on 2023-06-30 20:53

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_auto_20230630_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='create_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='task',
            name='number',
            field=models.UUIDField(default=uuid.UUID('9fa1be98-1fbd-4a40-bdba-87b7e7b7c338'), editable=False, unique=True, verbose_name='Номер задачи'),
        ),
        migrations.AlterField(
            model_name='task',
            name='update_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата обновления'),
        ),
    ]
