# Generated by Django 3.2.19 on 2023-07-01 09:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_auto_20230630_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='number',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Номер задачи'),
        ),
    ]
